json.errors t(:not_found, scope: "api.errors")